### ISSUE TITLE
Hi Frend, i may find a mistake in tinyscroll.js

### ISSUE THREAD

**Issue by CNSH-Leo** [FrendEr/tinyscroll.js#2]
I think "this.time" should be "this.options.time".
And in your demo, since there is no this logic, so the demo runs well.

Please forgive me, if I got that all wrong. ^.^

line 240 : 
          if (this.time) {
                return year + '-' +
                    (month  > 9 ? month  : ('0' + month))  + '-' +
                    (day    > 9 ? day    : ('0' + day))    + ' ' +
                    (hour   > 9 ? hour   : ('0' + hour))   + ':' +
                    (minute > 9 ? minute : ('0' + minute)) + ':' +
                    '00';
            } else {
                return year + '-' +
                    (month  > 9 ? month  : ('0' + month))  + '-' +
                    (day    > 9 ? day    : ('0' + day));
            }

**Comment by FrendEr** [comment]
@CNSH-Leo fix! thanks!
